
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:

  Package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp7/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: rake build_dependencies:install

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Package Build
      run: yast-ci-ruby -o package
